[workspace]
members = [
    "crab-admin",
    "crab-excel",
    "crab-excel-derive",
    "crab-config",
    "crab-cache",
    "crab-model",
    "crab-common",
    "crab-service",
    "crab-util",
    "crab-lib",
    "generator",
]
