# 数据库地址
database_url = "mysql://root:root@localhost:3306/hairy-crab"

# redis地址
redis_url = "redis://127.0.0.1:6379/"

# 日志目录
log_dir = "target/logs/"

# JWT 密钥
jwt_secret = "abcdefghijklmnopqrstuvwxyz"

# 白名单
white_list = ["/api/login", "/api/captcha"]

[server]
# 服务名称
name = "Hairy Crab"
# 服务地址
host = "127.0.0.1"
# 服务端口
port = 9999


# 逻辑删除字段
[logic]
# 列名
column = "del"
# 正常
normal = 0
# 已删除
deleted = 1
