[package]
name = "crab-admin"
version = "0.1.0"
edition = "2021"

[dependencies]
# web
poem = "1.0.34"
# poem-openapi = { version = "1.0.37", features = ["swagger-ui", "rapidoc"] }

# 序列化
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.72"

# 异步运行时
tokio = "1.14.0"

lazy_static = "1.4.0"

# DB相关
rbatis = { version = "3.0.24", default-features = false, features = [
    "mysql",
    "runtime-tokio-rustls",
    "debug_mode",
] }
bson2 = "2.0.3"
log = "0.4.14"
fast_log = "1.3.32"

# 错误传递
anyhow = "1.0.51"
