[package]
name = "crab-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crab-lib = { path = "../crab-lib" }
crab-model = { path = "../crab-model" }
crab-common = { path = "../crab-common" }
